### ISSUE TITLE
Fail to start

### ISSUE THREAD

**Issue by gyillikci** [AlexSpradling/Capella#2]
Hi,

Thanks for the work, I was trying to run it but couldn't achieved it. I am having an error about ttkboostrap as below

user@user-HP-ZBook-15-G5:~/.local/lib/python3.6/site-packages$ python3 capella/
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "capella/__main__.py", line 4, in <module>
    from ttkbootstrap.window import Window
ModuleNotFoundError: No module named 'ttkbootstrap.window'

Do you have any suggestions?

Best

**Comment by AlexSpradling** [comment]
If you run `pip show ttkboostrap` do you get version 1.10.1 ?

**Comment by gyillikci** [comment]
I do use pip3 instead of pip. and when I run it i get 0.5.3 as seen below

_Name: ttkbootstrap
Version: 0.5.3
Summary: A collection of modern ttk themes inspired by Bootstrap
Home-page: https://github.com/israel-dryer/ttkbootstrap
Author: Israel Dryer
Author-email: israel.dryer@gmail.com
License: UNKNOWN
Location: /home/user/.local/lib/python3.6/site-packages
Requires: pillow_

**Comment by AlexSpradling** [comment]
> I do use pip3 instead of pip. and when I run it i get 0.5.3 as seen below
> 
> 
> 
> _Name: ttkbootstrap
> 
> Version: 0.5.3
> 
> Summary: A collection of modern ttk themes inspired by Bootstrap
> 
> Home-page: https://github.com/israel-dryer/ttkbootstrap
> 
> Author: Israel Dryer
> 
> Author-email: israel.dryer@gmail.com
> 
> License: UNKNOWN
> 
> Location: /home/user/.local/lib/python3.6/site-packages
> 
> Requires: pillow_
> 
> 
> 
> 
> 
> When I do try to install with pip then I got no matching distro found. By the way, I am using an Ubuntu18.04
> 
> user@user-HP-ZBook-15-G5:~/Capella/capella$ python -m pip install ttkbootstrap
> 
> Collecting ttkbootstrap
> 
>   Could not find a version that satisfies the requirement ttkbootstrap (from versions: )
> 
> No matching distribution found for ttkbootstrap
> 
> 

Ok, just upgrade to the latest version and you should be good to go!
